version: "3.9"
 
services: 
  syslogd: 
    build:
      context: .
    image: rsyslog:custom
    container_name: rsyslog 
    hostname: rsyslog 
    restart: always
    volumes: 
      - rsyslog_home:/var/log
    ports: 
      - 514:514
      - 514:514/udp
    cap_add:
      - SYSLOG
    environment:
      - TZ=America/New_York

volumes:
  rsyslog_home:
    name: rsyslog_home
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_VOLUMES}/rsyslog
