version: "3.9"
 
services: 
  syslogd: 
    build:
      context: .
    image: rsyslog:custom
    container_name: rsyslog 
    hostname: rsyslog 
    restart: always
    volumes: 
      - rsyslog_home:/var/log
    networks:
      - rsyslog_network
    ports: 
      - ${RSYSLOG_PORT}:514
      - ${RSYSLOG_PORT}:514/udp
    cap_add:
      - SYSLOG
    environment:
      - TZ=${TIME_ZONE}

networks:
  rsyslog_network:
    name: rsyslog_network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${RSYSLOG_SUBNET_PREFIX}.0/24
          gateway: ${RSYSLOG_SUBNET_PREFIX}.1

volumes:
  rsyslog_home:
    name: rsyslog_home
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_VOLUMES}/rsyslog
