version: '3.9'
services:
   mysql:
     image: mysql:5.7
     container_name: redmine_mysql
     hostname: redmine_mysql
     volumes:
       - /usr/local/storage/redmine/mysql:/var/lib/mysql
     environment:
       MYSQL_DATABASE: redmine
       MYSQL_USER: redmine
       MYSQL_PASSWORD: $DB_PASSWORD
       MYSQL_ROOT_PASSWORD: $DB_PASSWORD
     restart: always
   redmine:
     build:
       context: .
     image: redmine:custom
     container_name: redmine
     hostname: redmine
     depends_on:
       - mysql
     restart: always
     ports:
       - 3000:3000
     environment:
       DB_ADAPTER: mysql2
       REDMINE_DB_MYSQL: mysql
       REDMINE_DB_PASSWORD: $DB_PASSWORD
       SMTP_ADDRESS: $SMTP_ADDRESS

     volumes:
       - /usr/local/storage/redmine/plugins:/usr/src/redmine/plugins
       - /usr/local/storage/redmine/public/themes:/usr/src/redmine/public/themes
       - /usr/local/storage/redmine/files:/usr/src/redmine/files
       - /usr/local/storage/redmine/repos:/var/lib/redmine/repos
