version: '3.9'
services:
  mysql:
    image: mysql:5.7
    platform: linux/amd64
    container_name: redmine_mysql
    hostname: redmine_mysql
    networks:
      - redmine_network
    volumes:
      - redmine_mysql_home:/var/lib/mysql
    environment:
      MYSQL_DATABASE: redmine
      MYSQL_USER: redmine
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
    restart: always
  redmine:
    build:
      context: .
    image: redmine:custom
    container_name: redmine
    hostname: redmine
    depends_on:
      - mysql
    restart: always
    networks:
      - redmine_network
      - postfix_network
    ports:
      - ${REDMINE_PORT}:3000
    environment:
      - DB_ADAPTER=mysql2
      - REDMINE_DB_MYSQL=mysql
      - REDMINE_DB_PASSWORD=$DB_PASSWORD
      - SMTP_ADDRESS=postfix
      - TZ=${TIME_ZONE}
    logging:
      driver: syslog
      options:
        syslog-address: "udp://${RSYSLOG_SUBNET_PREFIX}.1:${RSYSLOG_PORT}"
        syslog-format: "${RSYSLOG_FORMAT}"
        tag: "{{.Name}}/{{.ID}}"
    volumes:
      - redmine_plugins:/usr/src/redmine/plugins
      - redmine_themes:/usr/src/redmine/public/themes
      - redmine_files:/usr/src/redmine/files
      - redmine_gitroot:/var/lib/redmine/repos

networks:
  redmine_network:
    name: redmine_network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${REDMINE_SUBNET_PREFIX}.0/24
          gateway: ${REDMINE_SUBNET_PREFIX}.1
  postfix_network:
    external: true

volumes:
  redmine_plugins:
    name: redmine_plugins
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_VOLUMES}/redmine/plugins
  redmine_themes:
    name: redmine_themes
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_VOLUMES}/redmine/public/themes
  redmine_files:
    name: redmine_files
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_VOLUMES}/redmine/files
  redmine_mysql_home:
    name: redmine_mysql_home
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_VOLUMES}/redmine/mysql
  redmine_gitroot:
    name: redmine_gitroot
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_VOLUMES}/redmine/gitroot
