version: '3.9'
services:
   mysql:
     image: mysql:5.7
     container_name: redmine_mysql
     hostname: redmine_mysql
     volumes:
       - redmine_mysql_home:/var/lib/mysql
     networks:
       - db_network
     environment:
       MYSQL_DATABASE: redmine
       MYSQL_USER: redmine
       MYSQL_PASSWORD: $DB_PASSWORD
       MYSQL_ROOT_PASSWORD: $DB_PASSWORD
     env_file:
       - .env
     restart: always
   redmine:
     build:
       context: .
     image: redmine:custom
     container_name: redmine
     hostname: redmine
     depends_on:
       - mysql
     restart: always
     networks:
       - postfix_network
       - db_network
     ports:
       - 3000:3000
     environment:
       DB_ADAPTER: mysql2
       REDMINE_DB_MYSQL: mysql
       REDMINE_DB_PASSWORD: $DB_PASSWORD
       SMTP_ADDRESS: postfix
     volumes:
       - redmine_home:/data
       - redmine_gitroot:/var/lib/redmine/repos

networks:
  postfix_network:
    external: true
  db_network:
    name: redmine_db_network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${DB_SUBNET_PREFIX}.0/24
          gateway: ${DB_SUBNET_PREFIX}.1

volumes:
  redmine_home:
    name: redmine_home
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_VOLUMES}/redmine
  redmine_mysql_home:
    name: redmine_mysql_home
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_VOLUMES}/redmine/mysql
  redmine_gitroot:
    name: redmine_gitroot
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_VOLUMES}/redmine/gitroot
