version: '3.9'

services:
  gitea:
    image: gitea/gitea:1.21
    container_name: gitea
    hostname: gitea
    restart: always
    networks:
      - gitea_network
      - postfix_network
    ports:
      - "${GITEA_HTTP_PORT}:3000"
      - "${GITEA_SSH_PORT}:22"
    volumes:
      - gitea_data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=sqlite3
      - GITEA__database__PATH=/data/gitea/gitea.db
      - GITEA__server__DOMAIN=${GITEA_DOMAIN}
      - GITEA__server__SSH_DOMAIN=${GITEA_DOMAIN}
      - GITEA__server__ROOT_URL=http://${GITEA_DOMAIN}:${GITEA_HTTP_PORT}/
      - GITEA__server__SSH_PORT=${GITEA_SSH_PORT}
      - GITEA__server__DISABLE_SSH=false
      - GITEA__server__START_SSH_SERVER=true
      - GITEA__mailer__ENABLED=true
      - GITEA__mailer__SMTP_ADDR=postfix
      - GITEA__mailer__SMTP_PORT=587
      - GITEA__mailer__FROM=${GITEA_ADMIN_EMAIL}
      - GITEA__service__DISABLE_REGISTRATION=${GITEA_DISABLE_REGISTRATION}
      - GITEA__service__REQUIRE_SIGNIN_VIEW=${GITEA_REQUIRE_SIGNIN_VIEW}
      - TZ=${TIME_ZONE}
    logging:
      driver: syslog
      options:
        syslog-address: "udp://${RSYSLOG_SUBNET_PREFIX}.1:${RSYSLOG_PORT}"
        syslog-format: "${RSYSLOG_FORMAT}"
        tag: "{{.Name}}/{{.ID}}"

networks:
  gitea_network:
    name: gitea_network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${GITEA_SUBNET_PREFIX}.0/24
          gateway: ${GITEA_SUBNET_PREFIX}.1
  postfix_network:
    external: true

volumes:
  gitea_data:
    name: gitea_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_VOLUMES}/gitea/data
