version: '3.8'
services:
  postfix:
    build:
      context: .
    image: postfix-custom
    container_name: postfix
    restart: always
    environment:
      - SMTP_USERNAME=$SMTP_USERNAME
      - SMTP_PASSWORD=$SMTP_PASSWORD
    env_file:
      - env
    ports:
       - 25:25