version: '3.9'

services:
  postfix:
    build:
      context: .
    networks:
      - postfix_network
      - rsyslog_network
    image: postfix:custom
    container_name: postfix
    hostname: postfix
    restart: always
    env_file:
      - .env
    environment:
      - SMTP_USERNAME=$SMTP_USERNAME
      - SMTP_PASSWORD=$SMTP_PASSWORD
      - TZ=${TIME_ZONE}
    logging:
      driver: syslog
      options:
        syslog-address: "udp://${RSYSLOG_SUBNET_PREFIX}.1:${RSYSLOG_PORT}"
        syslog-format: "${RSYSLOG_FORMAT}"
        tag: "{{.Name}}/{{.ID}}"
    ports:
       - "${POSTFIX_PORT}:25"
    cap_add:
      - SYSLOG

networks:
  postfix_network:
    name: postfix_network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${POSTFIX_SUBNET_PREFIX}.0/24
          gateway: ${POSTFIX_SUBNET_PREFIX}.1
  rsyslog_network:
    external: true
