version: '3.9'

services:
  beancount:
    build:
      context: .
    image: beancount
    container_name: beancount
    hostname: fava
    volumes:
       - $BEAN_DIR:/bean
    restart: always
    ports:
       - "5555:5000"
