version: '3.9'

services:
  beancount:
    build:
      context: .
    image: beancount
    container_name: beancount
    hostname: fava
    volumes:
       - bean_home:/bean
    restart: always
    networks:
      - fava_network
    ports:
       - "${FAVA_PORT}:5000"
    environment:
      - TZ=${TIME_ZONE}
    logging:
      driver: syslog
      options:
        syslog-address: "udp://${RSYSLOG_SUBNET_PREFIX}.1:${RSYSLOG_PORT}"
        syslog-format: "${RSYSLOG_FORMAT}"
        tag: "{{.Name}}/{{.ID}}"

volumes:
  bean_home:
    name: bean_home
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${BEAN_DIR}

networks:
  fava_network:
    name: fava_network
