version: '3.9'

services:
  beancount:
    build:
      context: .
    image: beancount
    container_name: beancount
    hostname: fava
    volumes:
       - bean_home:/bean
    restart: always
    networks:
      - fava_network
    ports:
       - "5555:5000"

volumes:
  bean_home:
    name: bean_home
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${BEAN_DIR}

networks:
  fava_network:
    name: fava_network
