version: '3.9'

services:
  nginx:
    build:
      context: .
    image: nginx:custom
    container_name: nginx
    hostname: nginx
    networks:
      - nginx_network
      - jenkins_network
      - syncthing_network
      - redmine_network
      - fava_network
    restart: unless-stopped
    ports:
      - "${NGINX_PORT}:80"
      - "${NGINX_PORT2}:443"
    # volumes:
    #   - nginx_home:/var/www/html
    environment:
      - TZ=${TIME_ZONE}
    logging:
      driver: syslog
      options:
        syslog-address: "udp://${RSYSLOG_SUBNET_PREFIX}.1:${RSYSLOG_PORT}"
        syslog-format: "${RSYSLOG_FORMAT}"
        tag: "{{.Name}}/{{.ID}}"

# volumes:
#   nginx_home:
#     name: nginx_home
#     driver: local
#     driver_opts:
#       type: none
#       o: bind
#       device: ${DOCKER_VOLUMES}/nginx

networks:
  nginx_network:
    name: nginx_network
  jenkins_network:
    external: true
  syncthing_network:
    external: true
  redmine_network:
    external: true
  fava_network:
    external: true
