version: '3.9'

services:
  jenkins:
    build:
      context: .
    image: jenkins:custom
    container_name: jenkins
    hostname: jenkins
    privileged: true
    user: root
    networks:
      - jenkins_network
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - jenkins_home:/var/jenkins_home
    environment:
      - TZ=America/New_York

  agent:
    build:
      context: agent
    container_name: jenkins_agent
    restart: always
    hostname: agent
    privileged: true
    user: root
    networks:
      - jenkins_network
      - postfix_network
      - redmine_db_network
      - smartrade_mongodb
    expose:
      - 22
    volumes:
      - jenkins_home:/var/jenkins_home
      - gitwork_home:/usr/src
      - data_bak:/data/backups
    depends_on:
      - jenkins
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=${JENKINS_AGENT_SSH_PUBKEY}
      - TZ=America/New_York

volumes:
  jenkins_home:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_VOLUMES}/jenkins
  data_bak:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_BAK}
  gitwork_home:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${GITWORK_HOME}

networks:
  jenkins_network:
    name: jenkins_network
  postfix_network:
    external: true
  redmine_db_network:
    external: true
  smartrade_mongodb:
    external: true
