version: '3.9'

services:
  jenkins:
    build:
      context: .
    image: jenkins:custom
    container_name: jenkins
    hostname: jenkins
    privileged: true
    user: root
    networks:
      - jenkins_network
      - rsyslog_network
    ports:
      - "${JENKINS_PORT}:8080"
      - "${JENKINS_PORT2}:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    environment:
      - TZ=${TIME_ZONE}
    logging:
      driver: syslog
      options:
        syslog-address: "udp://${RSYSLOG_SUBNET_PREFIX}.1:${RSYSLOG_PORT}"
        syslog-format: "${RSYSLOG_FORMAT}"
        tag: "{{.Name}}/{{.ID}}"

  agent:
    build:
      context: agent
    container_name: jenkins_agent
    restart: always
    hostname: agent
    privileged: true
    user: root
    networks:
      - jenkins_network
      - rsyslog_network
      - postfix_network
      - redmine_network
    expose:
      - 22
    volumes:
      - jenkins_home:/var/jenkins_home
      - src_home:/usr/src
      - data_bak:/data/backups
    depends_on:
      - jenkins
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=${JENKINS_AGENT_SSH_PUBKEY}
      - TZ=${TIME_ZONE}
    logging:
      driver: syslog
      options:
        syslog-address: "udp://${RSYSLOG_SUBNET_PREFIX}.1:${RSYSLOG_PORT}"
        syslog-format: "${RSYSLOG_FORMAT}"
        tag: "{{.Name}}/{{.ID}}"

volumes:
  jenkins_home:
    name: jenkins_home
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_VOLUMES}/jenkins
  data_bak:
    name: jenkins_data_bak
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_BAK}
  src_home:
    name: jenkins_src_home
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${GITWORK_HOME}

networks:
  jenkins_network:
    name: jenkins_network
  rsyslog_network:
    external: true
  postfix_network:
    external: true
  redmine_network:
    external: true
