version: '3.9'

services:
  utils:
    build:
      context: .
    image: utils
    container_name: utils
    platform: linux/x86_64
    environment:
      - TZ=${TIME_ZONE}
    logging:
      driver: syslog
      options:
        syslog-address: "udp://${RSYSLOG_SUBNET_PREFIX}.1:${RSYSLOG_PORT}"
        syslog-format: "${RSYSLOG_FORMAT}"
        tag: "{{.Name}}/{{.ID}}"
