version: '3.9'

services:
  syncthing:
    #image: lscr.io/linuxserver/syncthing
    image: syncthing/syncthing
    container_name: syncthing
    hostname: syncthing
    networks:
      - syncthing_network
    ports:
      - ${SYNCTHING_PORT_WEB}:8384 # Web UI
      - ${SYNCTHING_PORT_TCP}:22000/tcp # TCP file transfers
      - ${SYNCTHING_PORT_QUIC}:22000/udp # QUIC file transfers
      - ${SYNCTHING_PORT_DISCOVERY}:21027/udp # Receive local discovery broadcasts
    volumes:
      - syncthing_home:/var/syncthing
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIME_ZONE}
    logging:
      driver: syslog
      options:
        syslog-address: "udp://${RSYSLOG_SUBNET_PREFIX}.1:${RSYSLOG_PORT}"
        syslog-format: "${RSYSLOG_FORMAT}"
        tag: "{{.Name}}/{{.ID}}"
    restart: unless-stopped

networks:
  syncthing_network:
    name: syncthing_network

volumes:
  syncthing_home:
    name: syncthing_home
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_VOLUMES}/syncthing
